// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingServer.Repository;

namespace ParkingServer.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211116080857_AddPaymentsTable")]
    partial class AddPaymentsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingServer.Repository.Entities.ParkingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllSpaces")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("FreeSpacesLeft")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("ParkingData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllSpaces = 100,
                            Description = "My super duper cool parking.",
                            FreeSpacesLeft = 100,
                            Name = "Rosen's Parking"
                        });
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.ParkingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LicensePlte")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("PriceRangeId")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredVehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOfLeave")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PriceRangeId");

                    b.HasIndex("RegisteredVehicleId");

                    b.ToTable("ParkingStatus");
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParkingStatusId")
                        .HasColumnType("int");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParkingStatusId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.PriceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PriceRange");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Price = 0.5
                        },
                        new
                        {
                            Id = 3,
                            Price = 1.0
                        });
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.RegisteredVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("PriceRangeId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("PriceRangeId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("RegisteredVehicles");
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Ambulance"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Police Car"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Fire Truck"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Ambulance"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Company Car"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Paid Subscription"
                        });
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.ParkingStatus", b =>
                {
                    b.HasOne("ParkingServer.Repository.Entities.PriceRange", "PriceRange")
                        .WithMany("ParkingStatuses")
                        .HasForeignKey("PriceRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingServer.Repository.Entities.RegisteredVehicle", "RegisteredVehicle")
                        .WithMany("ParkingStatuses")
                        .HasForeignKey("RegisteredVehicleId");
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.Payment", b =>
                {
                    b.HasOne("ParkingServer.Repository.Entities.ParkingStatus", "ParkingStatus")
                        .WithOne("Payment")
                        .HasForeignKey("ParkingServer.Repository.Entities.Payment", "ParkingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParkingServer.Repository.Entities.RegisteredVehicle", b =>
                {
                    b.HasOne("ParkingServer.Repository.Entities.PriceRange", "PriceRange")
                        .WithMany("RegisteredVehicles")
                        .HasForeignKey("PriceRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingServer.Repository.Entities.VehicleType", "VehicleType")
                        .WithMany("RegisteredVehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
